Moves testing under main project
This did not bring anything to the lib + it now causes an issue with angular compilation
Example of error :
testing/src/lib/mapper.service.mock.ts:4:39 - error TS6059: File 'D:/Github/ngx-logger/src/lib/mapper/ilog-position.ts' is not under 'rootDir' 'D:\Github\ngx-logger\testing\src'. 'rootDir' is expected to contain all source files.
  The file is in the program because:
    Imported via 'src/lib/mapper/ilog-position' from file 'D:/Github/ngx-logger/testing/src/lib/mapper.service.mock.ts'
    Imported via "./ilog-position" from file 'D:/Github/ngx-logger/src/lib/mapper/imapper.service.ts'

PS : This should be done in another pr/branch but I don't have enough time for that